# Generated by Django 4.2 on 2024-01-03 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_module_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.module')),
                ('age', models.CharField(max_length=50)),
            ],
            bases=('api.module',),
        ),
    ]
